name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy na VPS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ secrets.PROJECT_PATH }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch origin main
            git reset --hard origin/main
            git clean -fxd -e .env
            cp .env .env.production
            sudo /usr/sbin/semanage fcontext -a -t httpd_sys_script_exec_t "/home/packetads(/.*)?" 2> /dev/null
            sudo /usr/sbin/restorecon -R /home/packetads 2> /dev/null
            sudo /usr/bin/chcon -t bin_t /home/packetads/.local/share/pnpm/bin/pnpm
            /home/packetads/.local/share/pnpm/bin/pnpm install 
            /home/packetads/.local/share/pnpm/bin/pnpm build
            sudo /usr/bin/systemctl restart packetads.service
            